language: erlang
script: mix do clean, test
otp_release:
  - R16B
before_install:
  - mkdir -p vendor/elixir
  - git clone --quiet https://github.com/elixir-lang/elixir.git vendor/elixir
  - make --quiet -C vendor/elixir > /dev/null 2>&1
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - rm -rf deps
  - MIX_ENV=test mix deps.get
