language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
      script: mix test
    - otp_release: 19.0
      elixir: 1.3.2
      script: mix test
    - otp_release: 18.3
      elixir: 1.4.2
    - otp_release: 19.0
      elixir: 1.4.2
sudo: false
before_script:
  - mix deps.get --only test
script: mix test
