language: erlang
script: MIX_ENV=test mix do clean, test
cache:
  directories:
  - vendor/elixir
otp_release:
  - 17.0
before_install:
  - mkdir -p vendor/elixir
  - git clone --quiet https://github.com/elixir-lang/elixir.git vendor/elixir
  - make --quiet -C vendor/elixir > /dev/null 2>&1
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - rm -rf deps
  - MIX_ENV=test mix deps.get
